.PHONY: help dev-backend dev-frontend build up down restart \
        migrate migrate-auto seed logs test lint typecheck \
        clean shell-backend shell-frontend shell-db

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "$(BLUE)%-20s$(NC) %s\n", $$1, $$2}'

BLUE  := \033[0;34m
NC    := \033[0m

# ---- Development ----

dev-backend: ## Start the backend in development mode
	cd backend && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

dev-frontend: ## Start the frontend in development mode
	cd frontend && npm run dev

# ---- Docker ----

build: ## Build all Docker images
	docker-compose build --parallel

up: ## Start all Docker containers
	docker-compose up -d

down: ## Stop all Docker containers
	docker-compose down

restart: ## Restart all Docker containers
	docker-compose restart

logs: ## Show Docker logs (use svc=name to filter)
	docker-compose logs -f $(svc)

ps: ## List running containers
	docker-compose ps

# ---- Database ----

migrate: ## Run database migrations to head
	cd backend && alembic upgrade head

migrate-auto: ## Create an autogenerated migration
	cd backend && alembic revision --autogenerate -m "$(msg)"

migrate-downgrade: ## Rollback last migration
	cd backend && alembic downgrade $(rev)

migrate-history: ## Show migration history
	cd backend && alembic history

seed: ## Seed the database with sample data
	cd backend && python scripts/seed.py

seed-docker: ## Seed the database inside Docker
	docker exec -e PYTHONPATH=/app officeai-backend python scripts/seed.py

# ---- Testing ----

test: ## Run backend tests
	cd backend && python -m pytest tests/ -v --tb=short

test-coverage: ## Run backend tests with coverage
	cd backend && python -m pytest tests/ -v --tb=short --cov=app --cov-report=term --cov-report=html

test-frontend: ## Run frontend tests
	cd frontend && npm test

# ---- Linting & Type Checking ----

lint: ## Run linters
	cd backend && ruff check .
	cd backend && ruff format --check .

lint-fix: ## Fix linting issues
	cd backend && ruff check --fix .
	cd backend && ruff format .

typecheck: ## Run type checking
	cd backend && mypy app
	cd frontend && npm run typecheck

# ---- Utility ----

shell-backend: ## Open a shell in the backend container
	docker exec -it officeai-backend /bin/bash

shell-frontend: ## Open a shell in the frontend container
	docker exec -it officeai-frontend /bin/sh

shell-db: ## Open a PostgreSQL shell
	docker exec -it officeai-postgres psql -U postgres -d officeai

clean: ## Clean up Python and Node artifacts
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete
	rm -rf .pytest_cache .mypy_cache .ruff_cache
	rm -rf frontend/.next frontend/out
	rm -rf backend/*.egg-info
	rm -rf htmlcov coverage
	@echo "Clean complete"
